

target 'LTBaiDuLocation_Example' do
    
  pod 'LTLocation', :git => 'git@github.com:yelon21/LTLocation.git'

  pod 'LTBaiDuLocation', :path => '../'

  target 'LTBaiDuLocation_Tests' do
    inherit! :search_paths

    
  end
end
